### ISSUE TITLE
Use --job-dir instead of --output_dir

### ISSUE THREAD

**Issue by elibixby** [vijaykyr/tensorflow_teaching_examples#2]
`--output_dir` is deprecated. gcloud uses --job-dir in hyperparameter tuning to scope training jobs by their `trial_id`. Additionally even outside of hptuning CMLE will validate the existence of paths, making `--job-dir` useful.

**Comment by vijaykyr** [comment]
Finally getting around to this. I tried removing output_dir but it's still a required argument. If I remove it jobs fail with the message "task.py: error: argument --output_dir is required"

**Comment by elibixby** [comment]
You should be using --job-dir and replacing the output_dir command, and then passing --job-dir. This is because hptuning uses job-dir and also CMLE will validate job-dir.

**Comment by vijaykyr** [comment]
This is the existing format which works:
gcloud ml-engine jobs submit training $JOBNAME \
   --region=$REGION \
   --module-name=trainer.task \
   --package-path=./trainer \
   --job-dir=$GCS_BUCKET/$JOBNAME/ \
   -- \
   --output_dir=$GCS_BUCKET/$JOBNAME/output

This is what I think you're asking me to change it to, which gives the error I mentioned:
gcloud ml-engine jobs submit training $JOBNAME \
   --region=$REGION \
   --module-name=trainer.task \
   --package-path=./trainer \
   --job-dir=$GCS_BUCKET/$JOBNAME/ \
   -- \
   --job-dir=$GCS_BUCKET/$JOBNAME/output

Or do you mean something different?

**Comment by elibixby** [comment]
Why are you specifying job-dir twice? Just remove the second one. `--job-dir` is passed through as a command line argument after validation by the service.
